### ISSUE TITLE
Parametros da API de cutout em conformidade com protocolo VO SODA

### ISSUE THREAD

**Issue by glaubervila** [linea-it/cutout#10]
Está é uma das etapas necessárias para implementar o protocolo SODA. 
Está etapa vai cobrir apenas os parametros necessários para implementação do caso de uso SYNC. 
As demais demandas do protocolo serão cobertas na issue #14 

Analise e Avaliação dos Protocos e  implementação desses parametros no endpoint, 
[Protocolo SODA](https://wiki.ivoa.net/internal/IVOA/SODA/WD-SODA-1.0-20151221.pdf)
[Protocolo  SIA](https://www.ivoa.net/documents/SIA/20151223/REC-SIA-2.0-20151223.pdf)

[**IMPORTANTE EXEMPLO DA IMPLEMENTAÇÂO DO LSST VO CUTOUT:** ](https://github.com/lsst-sqre/vo-cutouts/blob/main/src/vocutouts/models/stencils.py)

no primeiro momento algumas opções não estaram finalizadas apenas mapeadas no código de forma a aparecer na documentação da API.

```[tasklist]
### Tasks
- [x] Definir os parametros que serão utilizados na criação do cutout.
- [x] Parametro ID ( No nosso caso identifica o Projeto DES ou LSST)
- [x] Parametro POS - Item 3.2.1 do protocolo SODA. ( Querys usando Circle, Range e Polygon)
- [ ] Parametro BAND - item 3.2.2 do protocolo SODA ( Internamente utilizamos bandas fixas "grizY" mas o protoco espera que valores numericos incluindo range, vamos precisar fazer uma mapeamento do valor numérico)
- [x] Parametro FORMAT - item 2.1.17 do protocolo SIA ( Nosso caso os formatos serão fits, png, jpg)
- [ ] Parametro CIRCLE - item 3.3.2 do Protocolo SODA ( este parametro é um atalho para o POS = Circle)
- [ ] Parametro POLYGON - item 3.3.3 do Protocolo SODA ( este parametro é um atalho para o POS = polygo)
- [x] Implementar Camada Policy para validação dos Parametros antes de submeter o Job.
- [x] Implementar registro dos parametros no modelo UWS (item 2.2.2.4 do UWS)
```
