### ISSUE TITLE
Acesso aos dados do DES entrada e saida do serviço de cutout.

### ISSUE THREAD

**Issue by glaubervila** [linea-it/cutout#13]
Configurar a aplicação de forma que permita o acesso aos arquivos Fits independente de uma extrutura fixa de diretórios. 
Cada Projeto (DES, LSST) deve ter sua propria estrutura de diretórios. a aplicação deve ser capaz acessar esses arquivos. 

Arquivos Fits DES.
```[tasklist]
### Tasks
- [x] Ambiente de desenvolvimento local. configurar diretórios compartilhado com o host no devcontainer.
- [x] Ambiente de validação/Produção. Acessar diretórios no Lustre.
- [x] Implementar metodo que permita identificar qual arquivo fits baseado em uma posição.
```
