### ISSUE TITLE
API de cutout conformidade com protocolo VO SODA

### ISSUE THREAD

**Issue by glaubervila** [linea-it/cutout#14]
Analise e Avaliação dos Protocos
[Protocolo SODA](https://wiki.ivoa.net/internal/IVOA/SODA/WD-SODA-1.0-20151221.pdf)
[Protocolo  SIA](https://www.ivoa.net/documents/SIA/20151223/REC-SIA-2.0-20151223.pdf)

```[tasklist]
### Tasks
- [ ] Endpoint SYNC resource item 2.1 do protocolo SODA
- [ ] Respostas de sucesso item 4.1 do protocolo SODA.
- [ ] Respostas de falhas item 4.2 do protocolo SODA.
```
